import React, { useEffect } from 'react';
import logo from '../../assets/ACG.png';
import Footer from './Footer';

const PLATFORM_RULES = [
  {
    name: 'Maximum risk per trade',
    value: '1% of current equity',
    detail: 'When a Stop Loss is set, the projected loss to that Stop Loss must not exceed 1% of current account equity. ACG does not require or automatically add a Stop Loss.',
  },
  {
    name: 'Maximum aggregate open risk',
    value: '2% of current equity',
    detail: 'When Stop Losses are present, the combined measurable risk across open positions must remain within 2% of current account equity.',
  },
  {
    name: 'Maximum margin usage',
    value: '50%',
    detail: 'New exposure must not increase total used margin above 50% of current account equity.',
  },
  {
    name: 'Maximum open positions',
    value: '10',
    detail: 'A trading account may have up to 10 open positions at the same time.',
  },
  {
    name: 'Maximum positions per symbol',
    value: '3',
    detail: 'A maximum of 3 open positions may be held on the same instrument at one time.',
  },
  {
    name: 'Maximum pending orders',
    value: '10',
    detail: 'A trading account may have up to 10 active pending orders at the same time.',
  },
  {
    name: 'Maximum pending orders per symbol',
    value: '3',
    detail: 'A maximum of 3 active pending orders may be placed on the same instrument at one time.',
  },
  {
    name: 'Single-order exposure',
    value: '20% of available margin capacity',
    detail: 'A single new order must not consume more than 20% of the account\'s available margin capacity at the time the order is evaluated.',
  },
  {
    name: 'Per-symbol gross exposure',
    value: '30% of permitted account exposure',
    detail: 'Gross exposure on one instrument must not exceed 30% of the total exposure permitted for the account. Opposing exposure is not netted down for this calculation.',
  },
];

const POLICY_RULES = [
  {
    title: 'News Trading',
    body: (
      <>
        <p>
          News trading availability depends on the challenge configuration selected by the trader.
          Where news trading is restricted, traders must not open or execute new positions within
          30 minutes before or 30 minutes after an applicable high-impact economic event.
        </p>
        <p>
          The setting shown for your challenge at purchase and in your account is the setting that
          applies to that challenge.
        </p>
      </>
    ),
  },
  {
    title: 'Hedging',
    body: (
      <p>
        Hedging is not permitted. Traders must not intentionally maintain opposing positions
        designed to offset the same market exposure or use hedging techniques to circumvent ACG
        challenge or risk rules.
      </p>
    ),
  },
  {
    title: 'Hedging Across Multiple Accounts',
    body: (
      <p>
        Coordinating opposite or offsetting positions across multiple ACG accounts is prohibited.
        This includes using separate evaluation or funded accounts to create an artificial hedge
        or to bypass account-level risk limits.
      </p>
    ),
  },
  {
    title: 'High-Frequency Trading (HFT)',
    body: (
      <p>
        High-frequency trading strategies designed to exploit execution speed, latency, price-feed
        delays, infrastructure behaviour, or rapid machine-driven order activity are not permitted.
      </p>
    ),
  },
  {
    title: 'Toxic Trading Behaviour',
    body: (
      <>
        <p>
          Tick scalping and arbitrage are strictly prohibited as described in Section 13i of the
          ACG Terms and Conditions.
        </p>
        <p>
          If more than 10% of your closed trades are held for less than one minute, or more than
          10% of your positive realized profits are generated by trades held for less than one
          minute, the account becomes temporarily ineligible for payout.
        </p>
        <p>
          You may continue trading until both percentages return to 10% or below. A continuous or
          repeated pattern of prohibited short-duration trading may result in account suspension or
          termination.
        </p>
      </>
    ),
  },
  {
    title: 'Account Sharing',
    body: (
      <p>
        Each trader is permitted only one active account per evaluation level unless ACG expressly
        states otherwise. Login credentials are personal and must not be shared. Trading on behalf
        of another person, or allowing another person to operate your account, is strictly
        prohibited.
      </p>
    ),
  },
];

function LimitCard({ rule }) {
  return (
    <article className="rounded-2xl border border-white/[0.08] bg-white/[0.025] p-5 sm:p-6">
      <div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between sm:gap-6">
        <h3 className="text-[14px] font-semibold tracking-[-0.015em] text-white">
          {rule.name}
        </h3>
        <span className="shrink-0 rounded-full border border-white/[0.09] bg-black/40 px-3 py-1 text-[11px] font-semibold text-[#D7DAE0]">
          {rule.value}
        </span>
      </div>
      <p className="mt-4 text-[12px] leading-6 text-[#858A94]">
        {rule.detail}
      </p>
    </article>
  );
}

export default function RulesPage() {
  useEffect(() => {
    const previousTitle = document.title;
    document.title = 'Trading Rules | ACG Funded';
    window.scrollTo({ top: 0, behavior: 'auto' });
    return () => { document.title = previousTitle; };
  }, []);

  return (
    <div className="min-h-screen bg-[#05060A] text-white">
      <header className="border-b border-white/[0.08] bg-[#05060A]/95">
        <div className="mx-auto flex max-w-[1224px] items-center justify-between px-6 py-5">
          <a href="/" aria-label="ACG Funded home">
            <img src={logo} width={82} alt="ACG Funded" />
          </a>
          <a
            href="/"
            className="text-[13px] font-medium text-[#969AA3] transition-colors hover:text-white"
          >
            Back to ACG Funded
          </a>
        </div>
      </header>

      <main>
        <section className="border-b border-white/[0.06]">
          <div className="mx-auto max-w-[1000px] px-6 py-16 sm:py-20">
            <p className="text-[11px] font-semibold uppercase tracking-[0.18em] text-[#737985]">
              ACG Funded
            </p>
            <h1 className="mt-3 max-w-3xl text-3xl font-semibold tracking-[-0.035em] text-white sm:text-5xl">
              Trading Rules
            </h1>
            <p className="mt-5 max-w-3xl text-[14px] leading-7 text-[#9499A3] sm:text-[15px]">
              These rules define the standard trading limits and conduct requirements that apply
              across ACG Funded programs. Challenge-specific settings shown at purchase or inside
              your account take precedence where a rule is configurable.
            </p>

            <div className="mt-8 grid gap-3 sm:grid-cols-3">
              <div className="rounded-xl border border-white/[0.07] bg-white/[0.02] px-4 py-4">
                <span className="block text-[10px] font-semibold uppercase tracking-[0.12em] text-[#6F7580]">Risk</span>
                <strong className="mt-1 block text-[14px] text-white">1% per trade · 2% aggregate</strong>
              </div>
              <div className="rounded-xl border border-white/[0.07] bg-white/[0.02] px-4 py-4">
                <span className="block text-[10px] font-semibold uppercase tracking-[0.12em] text-[#6F7580]">Margin</span>
                <strong className="mt-1 block text-[14px] text-white">50% maximum usage</strong>
              </div>
              <div className="rounded-xl border border-white/[0.07] bg-white/[0.02] px-4 py-4">
                <span className="block text-[10px] font-semibold uppercase tracking-[0.12em] text-[#6F7580]">Stop Loss</span>
                <strong className="mt-1 block text-[14px] text-white">Not mandatory</strong>
              </div>
            </div>
          </div>
        </section>

        <section className="mx-auto max-w-[1000px] px-6 py-14 sm:py-18">
          <div className="max-w-3xl">
            <p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-[#737985]">
              Platform limits
            </p>
            <h2 className="mt-2 text-2xl font-semibold tracking-[-0.03em]">
              Standard account restrictions
            </h2>
            <p className="mt-3 text-[13px] leading-6 text-[#858A94]">
              These limits are designed to control account exposure while leaving trade direction,
              Stop Loss and Take Profit decisions with the trader.
            </p>
          </div>

          <div className="mt-8 grid gap-3 md:grid-cols-2">
            {PLATFORM_RULES.map((rule) => <LimitCard key={rule.name} rule={rule} />)}
          </div>

          <div className="mt-14 rounded-2xl border border-white/[0.08] bg-white/[0.02] px-5 py-6 sm:px-7">
            <h3 className="text-[15px] font-semibold tracking-[-0.02em]">Stop Loss and measurable risk</h3>
            <p className="mt-3 text-[12px] leading-6 text-[#858A94]">
              ACG does not require a Stop Loss and does not automatically create or modify one.
              The 1% per-trade and 2% aggregate risk limits are measured from entry to Stop Loss
              only where a trader has chosen to set a Stop Loss. Positions without a Stop Loss
              remain subject to margin, single-order exposure, symbol exposure and position-count
              limits.
            </p>
          </div>
        </section>

        <section className="border-y border-white/[0.06] bg-white/[0.012]">
          <div className="mx-auto max-w-[1000px] px-6 py-14 sm:py-18">
            <div className="max-w-3xl">
              <p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-[#737985]">
                Trading conduct
              </p>
              <h2 className="mt-2 text-2xl font-semibold tracking-[-0.03em]">
                Strategy and account-use rules
              </h2>
              <p className="mt-3 text-[13px] leading-6 text-[#858A94]">
                These are ACG policy and compliance rules. Traders are responsible for ensuring
                their activity remains within the conditions of their program.
              </p>
            </div>

            <div className="mt-8 space-y-3">
              {POLICY_RULES.map((rule, index) => (
                <article
                  key={rule.title}
                  className="rounded-2xl border border-white/[0.08] bg-[#05060A] px-5 py-6 sm:px-7"
                >
                  <div className="flex items-start gap-4">
                    <span className="grid size-7 shrink-0 place-items-center rounded-full border border-white/[0.08] bg-white/[0.025] text-[10px] font-semibold text-[#7F858F]">
                      {String(index + 1).padStart(2, '0')}
                    </span>
                    <div>
                      <h3 className="text-[15px] font-semibold tracking-[-0.02em] text-white">
                        {rule.title}
                      </h3>
                      <div className="mt-3 space-y-3 text-[12px] leading-6 text-[#858A94]">
                        {rule.body}
                      </div>
                    </div>
                  </div>
                </article>
              ))}
            </div>
          </div>
        </section>

        <section className="mx-auto max-w-[1000px] px-6 py-14 sm:py-18">
          <div className="rounded-2xl border border-white/[0.08] bg-white/[0.025] px-5 py-6 sm:px-7 sm:py-7">
            <h2 className="text-[17px] font-semibold tracking-[-0.025em]">Important</h2>
            <div className="mt-4 space-y-3 text-[12px] leading-6 text-[#858A94]">
              <p>
                Challenge objectives such as profit targets, daily loss limits, maximum loss
                limits, minimum trading days and news-trading availability may vary by program.
                Always review the configuration shown for your specific challenge.
              </p>
              <p>
                These Trading Rules should be read together with the ACG Funded Terms &amp;
                Conditions. Where the Terms &amp; Conditions contain a more specific requirement,
                the Terms &amp; Conditions apply.
              </p>
            </div>
            <div className="mt-6 flex flex-wrap gap-3">
              <a
                href="/legal/terms-and-conditions"
                className="rounded-lg border border-white/[0.10] bg-white/[0.04] px-4 py-2.5 text-[12px] font-semibold text-white transition hover:bg-white/[0.07]"
              >
                Terms &amp; Conditions
              </a>
              <a
                href="mailto:support@acgfunded.com"
                className="rounded-lg px-4 py-2.5 text-[12px] font-medium text-[#8F949E] transition hover:text-white"
              >
                Questions? Contact support
              </a>
            </div>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  );
}
